export const DISCONNECTOR_SWITCH_CENTER = { x: -2, y: -2 };
export const DISCONNECTOR_SWITCH_OPEN = `rotate(-30 ${DISCONNECTOR_SWITCH_CENTER.x} ${DISCONNECTOR_SWITCH_CENTER.y})`;
export const DISCONNECTOR_SWITCH_CLOSE = `rotate(-10 ${DISCONNECTOR_SWITCH_CENTER.x} ${DISCONNECTOR_SWITCH_CENTER.y})`;
